server:
  port: 8081
spring:
  datasource:
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 12
      leak-detection-threshold: 10000
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    initialization-mode: always
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true