apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-db
      tier: backend
  template:
    metadata:
      labels:
        app: order-db
        tier: backend
    spec:
      containers:
        - name: order-db
          image: postgres:latest
          imagePullPolicy: "Always"
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: order-config
                  key: db_name
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: order-secret
                  key: db_user
            - name: POSTGRES_PASSWORD
              valueFrom:
                 secretKeyRef:
                   name: order-secret
                   key: db_pwd
          volumeMounts:
            - name: storage
              mountPath: /var/lib/postgresql/data
            - name: postgresql-initdb
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: postgres-pvc
        - name: postgresql-initdb
          configMap:
            name: postgresql-initdb-config