apiVersion: v1
kind: Service
metadata:
  name: order-db-service
spec:
  selector:
    app: order-db
  type: NodePort
  ports:
    - port: 5433
      targetPort: 5432
      nodePort: 30475
      protocol: TCP