apiVersion: v1
kind: Service
metadata:
  name: order-app-service
spec:
  selector:
    app: order-api
    tier: backend
  type: LoadBalancer
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30080
      protocol: TCP