apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-api
      tier: backend
  template:
     metadata:
       labels:
         app: order-api
         tier: backend
       annotations:
         prometheus.io/scrape: "true"
         prometheus.io/port: "8081"
         prometheus.io/path: "/actuator/prometheus"
     spec:
       containers:
         - name: order-api
           image: order_management:0.0.6
           imagePullPolicy: Never
           ports:
             - containerPort: 8081
           env:
             - name: DATABASE_URL
               valueFrom:
                 configMapKeyRef:
                   name: order-config
                   key: db_url
             - name: DATABASE_USERNAME
               valueFrom:
                 secretKeyRef:
                   name: order-secret
                   key: db_user
             - name: DATABASE_PASSWORD
               valueFrom:
                 secretKeyRef:
                   name: order-secret
                   key: db_pwd

