version: '3'

services:
  app:
    container_name: order_service
    image: order_management
    build: ..
    ports:
      - "8081:8081"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
    depends_on:
      - database
  database:
    container_name: order_db
    image: postgres:14
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PW}
    volumes:
      - ./infrastructure/db.sql:/docker-entrypoint-initdb.d/db.sql
      - order-data:/var/lib/postgresql/data #persist data even if container shuts down
volumes:
  order-data: # named volumes can be managed easier using docker-compose